### ISSUE TITLE
Crash when trying to access config

### ISSUE THREAD

**Issue by TotalDarkness-NRF** [ZekerZhayard/AutoReconnect#1]
Crash report: 
[autoreconnect-config-crash.txt](https://github.com/ZekerZhayard/AutoReconnect/files/9332865/autoreconnect-config-crash.txt)

Using the most recent build from [curseforge](https://www.curseforge.com/minecraft/mc-mods/autoreconnect-forge/download/3884705)

Tested building myself on the 1.18.x branch and it appears to be resolved.
Would recommend uploading most recent changes to curseforge as it appears everything is working on the 1.18.x branch.

Thanks for porting this mod to forge!

**Comment by ZekerZhayard** [comment]
Fixed, you can redownload the file from curseforge.
